# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-07 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0004_teacher_image'),
        ('courses', '0006_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgnization.Teacher', verbose_name='\u4efb\u8bfe\u6559\u5e08'),
        ),
    ]
