# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-07 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8bb2\u5e08\u544a\u8bc9\u4f60'),
        ),
    ]
