# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170807_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cource_notice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8bfe\u7a0b\u516c\u544a'),
        ),
    ]
